[tool.poetry]
name = "roki"
version = "0.1.0"
description = ""
authors = ["Rodrigo Eiti Kimura <rodrigoeitikimura@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
typer = "^0.12.5"
circuitpython-stubs = "^9.1.3"
pydantic = "^2.10.2"
minify-html = "^0.15.0"
jinja2 = "^3.1.4"
textual-dev = "^1.7.0"
fastapi = "^0.115.6"
uvicorn = "^0.34.0"

[tool.poetry.group.manager.dependencies]
rshell = "^0.0.33"
adafruit-ampy = "^1.1.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
commitizen = "^3.29.0"
pytest-cov = "^6.0.0"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "poetry"
update_changelog_on_bump = true
major_version_zero = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
roki = "roki.cli.app:app"

[tool.pytest.ini_options]
addopts = "--cov=roki --cov-report html --cov-report term"
